export default {
  login: "Adecodess",
  id: 66638496,
  node_id: "MDQ6VXNlcjY2NjM4NDk2",
  avatar_url: "https://avatars.githubusercontent.com/u/66638496?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Adecodess",
  html_url: "https://github.com/Adecodess",
  followers_url: "https://api.github.com/users/Adecodess/followers",
  following_url:
    "https://api.github.com/users/Adecodess/following{/other_user}",
  gists_url: "https://api.github.com/users/Adecodess/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Adecodess/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Adecodess/subscriptions",
  organizations_url: "https://api.github.com/users/Adecodess/orgs",
  repos_url: "https://api.github.com/users/Adecodess/repos",
  events_url: "https://api.github.com/users/Adecodess/events{/privacy}",
  received_events_url: "https://api.github.com/users/Adecodess/received_events",
  type: "User",
  site_admin: false,
  name: "Adecodess ",
  company: null,
  blog: "https://adecodess.netlify.app/",
  location: "Nigeria",
  email: null,
  hireable: null,
  bio: "Doing my best to use to tech to better my enviroment",
  twitter_username: "adetigerr",
  public_repos: 29,
  public_gists: 0,
  followers: 16,
  following: 21,
  created_at: "2020-06-08T17:19:08Z",
  updated_at: "2021-04-08T08:17:40Z",
};
