export default [
  {
    login: "AdetunjiTejumade",
    id: 46271302,
    node_id: "MDQ6VXNlcjQ2MjcxMzAy",
    avatar_url: "https://avatars.githubusercontent.com/u/46271302?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AdetunjiTejumade",
    html_url: "https://github.com/AdetunjiTejumade",
    followers_url: "https://api.github.com/users/AdetunjiTejumade/followers",
    following_url:
      "https://api.github.com/users/AdetunjiTejumade/following{/other_user}",
    gists_url: "https://api.github.com/users/AdetunjiTejumade/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AdetunjiTejumade/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AdetunjiTejumade/subscriptions",
    organizations_url: "https://api.github.com/users/AdetunjiTejumade/orgs",
    repos_url: "https://api.github.com/users/AdetunjiTejumade/repos",
    events_url:
      "https://api.github.com/users/AdetunjiTejumade/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AdetunjiTejumade/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Fuglydami",
    id: 66129867,
    node_id: "MDQ6VXNlcjY2MTI5ODY3",
    avatar_url: "https://avatars.githubusercontent.com/u/66129867?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Fuglydami",
    html_url: "https://github.com/Fuglydami",
    followers_url: "https://api.github.com/users/Fuglydami/followers",
    following_url:
      "https://api.github.com/users/Fuglydami/following{/other_user}",
    gists_url: "https://api.github.com/users/Fuglydami/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Fuglydami/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Fuglydami/subscriptions",
    organizations_url: "https://api.github.com/users/Fuglydami/orgs",
    repos_url: "https://api.github.com/users/Fuglydami/repos",
    events_url: "https://api.github.com/users/Fuglydami/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Fuglydami/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ahmedbelaid",
    id: 73943047,
    node_id: "MDQ6VXNlcjczOTQzMDQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/73943047?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ahmedbelaid",
    html_url: "https://github.com/Ahmedbelaid",
    followers_url: "https://api.github.com/users/Ahmedbelaid/followers",
    following_url:
      "https://api.github.com/users/Ahmedbelaid/following{/other_user}",
    gists_url: "https://api.github.com/users/Ahmedbelaid/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Ahmedbelaid/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ahmedbelaid/subscriptions",
    organizations_url: "https://api.github.com/users/Ahmedbelaid/orgs",
    repos_url: "https://api.github.com/users/Ahmedbelaid/repos",
    events_url: "https://api.github.com/users/Ahmedbelaid/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ahmedbelaid/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "oreakinwole",
    id: 47474885,
    node_id: "MDQ6VXNlcjQ3NDc0ODg1",
    avatar_url: "https://avatars.githubusercontent.com/u/47474885?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/oreakinwole",
    html_url: "https://github.com/oreakinwole",
    followers_url: "https://api.github.com/users/oreakinwole/followers",
    following_url:
      "https://api.github.com/users/oreakinwole/following{/other_user}",
    gists_url: "https://api.github.com/users/oreakinwole/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/oreakinwole/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/oreakinwole/subscriptions",
    organizations_url: "https://api.github.com/users/oreakinwole/orgs",
    repos_url: "https://api.github.com/users/oreakinwole/repos",
    events_url: "https://api.github.com/users/oreakinwole/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/oreakinwole/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "KenMan79",
    id: 51566205,
    node_id: "MDQ6VXNlcjUxNTY2MjA1",
    avatar_url: "https://avatars.githubusercontent.com/u/51566205?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/KenMan79",
    html_url: "https://github.com/KenMan79",
    followers_url: "https://api.github.com/users/KenMan79/followers",
    following_url:
      "https://api.github.com/users/KenMan79/following{/other_user}",
    gists_url: "https://api.github.com/users/KenMan79/gists{/gist_id}",
    starred_url: "https://api.github.com/users/KenMan79/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/KenMan79/subscriptions",
    organizations_url: "https://api.github.com/users/KenMan79/orgs",
    repos_url: "https://api.github.com/users/KenMan79/repos",
    events_url: "https://api.github.com/users/KenMan79/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/KenMan79/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nathanblaz",
    id: 24424412,
    node_id: "MDQ6VXNlcjI0NDI0NDEy",
    avatar_url: "https://avatars.githubusercontent.com/u/24424412?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nathanblaz",
    html_url: "https://github.com/nathanblaz",
    followers_url: "https://api.github.com/users/nathanblaz/followers",
    following_url:
      "https://api.github.com/users/nathanblaz/following{/other_user}",
    gists_url: "https://api.github.com/users/nathanblaz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nathanblaz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nathanblaz/subscriptions",
    organizations_url: "https://api.github.com/users/nathanblaz/orgs",
    repos_url: "https://api.github.com/users/nathanblaz/repos",
    events_url: "https://api.github.com/users/nathanblaz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nathanblaz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AMZEnterprise",
    id: 52137131,
    node_id: "MDQ6VXNlcjUyMTM3MTMx",
    avatar_url: "https://avatars.githubusercontent.com/u/52137131?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AMZEnterprise",
    html_url: "https://github.com/AMZEnterprise",
    followers_url: "https://api.github.com/users/AMZEnterprise/followers",
    following_url:
      "https://api.github.com/users/AMZEnterprise/following{/other_user}",
    gists_url: "https://api.github.com/users/AMZEnterprise/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AMZEnterprise/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AMZEnterprise/subscriptions",
    organizations_url: "https://api.github.com/users/AMZEnterprise/orgs",
    repos_url: "https://api.github.com/users/AMZEnterprise/repos",
    events_url: "https://api.github.com/users/AMZEnterprise/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AMZEnterprise/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Darko875",
    id: 36199541,
    node_id: "MDQ6VXNlcjM2MTk5NTQx",
    avatar_url: "https://avatars.githubusercontent.com/u/36199541?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Darko875",
    html_url: "https://github.com/Darko875",
    followers_url: "https://api.github.com/users/Darko875/followers",
    following_url:
      "https://api.github.com/users/Darko875/following{/other_user}",
    gists_url: "https://api.github.com/users/Darko875/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Darko875/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Darko875/subscriptions",
    organizations_url: "https://api.github.com/users/Darko875/orgs",
    repos_url: "https://api.github.com/users/Darko875/repos",
    events_url: "https://api.github.com/users/Darko875/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Darko875/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bacarPereira",
    id: 43761389,
    node_id: "MDQ6VXNlcjQzNzYxMzg5",
    avatar_url: "https://avatars.githubusercontent.com/u/43761389?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bacarPereira",
    html_url: "https://github.com/bacarPereira",
    followers_url: "https://api.github.com/users/bacarPereira/followers",
    following_url:
      "https://api.github.com/users/bacarPereira/following{/other_user}",
    gists_url: "https://api.github.com/users/bacarPereira/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bacarPereira/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/bacarPereira/subscriptions",
    organizations_url: "https://api.github.com/users/bacarPereira/orgs",
    repos_url: "https://api.github.com/users/bacarPereira/repos",
    events_url: "https://api.github.com/users/bacarPereira/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bacarPereira/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mena234",
    id: 53051308,
    node_id: "MDQ6VXNlcjUzMDUxMzA4",
    avatar_url: "https://avatars.githubusercontent.com/u/53051308?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mena234",
    html_url: "https://github.com/mena234",
    followers_url: "https://api.github.com/users/mena234/followers",
    following_url:
      "https://api.github.com/users/mena234/following{/other_user}",
    gists_url: "https://api.github.com/users/mena234/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mena234/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mena234/subscriptions",
    organizations_url: "https://api.github.com/users/mena234/orgs",
    repos_url: "https://api.github.com/users/mena234/repos",
    events_url: "https://api.github.com/users/mena234/events{/privacy}",
    received_events_url: "https://api.github.com/users/mena234/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Magicianred",
    id: 4624113,
    node_id: "MDQ6VXNlcjQ2MjQxMTM=",
    avatar_url: "https://avatars.githubusercontent.com/u/4624113?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Magicianred",
    html_url: "https://github.com/Magicianred",
    followers_url: "https://api.github.com/users/Magicianred/followers",
    following_url:
      "https://api.github.com/users/Magicianred/following{/other_user}",
    gists_url: "https://api.github.com/users/Magicianred/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Magicianred/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Magicianred/subscriptions",
    organizations_url: "https://api.github.com/users/Magicianred/orgs",
    repos_url: "https://api.github.com/users/Magicianred/repos",
    events_url: "https://api.github.com/users/Magicianred/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Magicianred/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "OdirleiLeite",
    id: 78909977,
    node_id: "MDQ6VXNlcjc4OTA5OTc3",
    avatar_url: "https://avatars.githubusercontent.com/u/78909977?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/OdirleiLeite",
    html_url: "https://github.com/OdirleiLeite",
    followers_url: "https://api.github.com/users/OdirleiLeite/followers",
    following_url:
      "https://api.github.com/users/OdirleiLeite/following{/other_user}",
    gists_url: "https://api.github.com/users/OdirleiLeite/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/OdirleiLeite/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/OdirleiLeite/subscriptions",
    organizations_url: "https://api.github.com/users/OdirleiLeite/orgs",
    repos_url: "https://api.github.com/users/OdirleiLeite/repos",
    events_url: "https://api.github.com/users/OdirleiLeite/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/OdirleiLeite/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Davien21",
    id: 54110155,
    node_id: "MDQ6VXNlcjU0MTEwMTU1",
    avatar_url: "https://avatars.githubusercontent.com/u/54110155?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Davien21",
    html_url: "https://github.com/Davien21",
    followers_url: "https://api.github.com/users/Davien21/followers",
    following_url:
      "https://api.github.com/users/Davien21/following{/other_user}",
    gists_url: "https://api.github.com/users/Davien21/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Davien21/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Davien21/subscriptions",
    organizations_url: "https://api.github.com/users/Davien21/orgs",
    repos_url: "https://api.github.com/users/Davien21/repos",
    events_url: "https://api.github.com/users/Davien21/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Davien21/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "meehawk",
    id: 80167324,
    node_id: "MDQ6VXNlcjgwMTY3MzI0",
    avatar_url: "https://avatars.githubusercontent.com/u/80167324?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/meehawk",
    html_url: "https://github.com/meehawk",
    followers_url: "https://api.github.com/users/meehawk/followers",
    following_url:
      "https://api.github.com/users/meehawk/following{/other_user}",
    gists_url: "https://api.github.com/users/meehawk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/meehawk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/meehawk/subscriptions",
    organizations_url: "https://api.github.com/users/meehawk/orgs",
    repos_url: "https://api.github.com/users/meehawk/repos",
    events_url: "https://api.github.com/users/meehawk/events{/privacy}",
    received_events_url: "https://api.github.com/users/meehawk/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jesulonimii",
    id: 70331030,
    node_id: "MDQ6VXNlcjcwMzMxMDMw",
    avatar_url: "https://avatars.githubusercontent.com/u/70331030?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jesulonimii",
    html_url: "https://github.com/jesulonimii",
    followers_url: "https://api.github.com/users/jesulonimii/followers",
    following_url:
      "https://api.github.com/users/jesulonimii/following{/other_user}",
    gists_url: "https://api.github.com/users/jesulonimii/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jesulonimii/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jesulonimii/subscriptions",
    organizations_url: "https://api.github.com/users/jesulonimii/orgs",
    repos_url: "https://api.github.com/users/jesulonimii/repos",
    events_url: "https://api.github.com/users/jesulonimii/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jesulonimii/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xdvrx1",
    id: 47092464,
    node_id: "MDQ6VXNlcjQ3MDkyNDY0",
    avatar_url: "https://avatars.githubusercontent.com/u/47092464?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xdvrx1",
    html_url: "https://github.com/xdvrx1",
    followers_url: "https://api.github.com/users/xdvrx1/followers",
    following_url: "https://api.github.com/users/xdvrx1/following{/other_user}",
    gists_url: "https://api.github.com/users/xdvrx1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xdvrx1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xdvrx1/subscriptions",
    organizations_url: "https://api.github.com/users/xdvrx1/orgs",
    repos_url: "https://api.github.com/users/xdvrx1/repos",
    events_url: "https://api.github.com/users/xdvrx1/events{/privacy}",
    received_events_url: "https://api.github.com/users/xdvrx1/received_events",
    type: "User",
    site_admin: false,
  },
];
